### ISSUE TITLE
Part of the 'Action/Properties' Panel is transparent

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1059]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190110.1
**Commit:** b4ffb306
**Regression From:** Previous release 1.6.2

#### Steps to Reproduce: ####
1. Focus one storage account/service.
2. Check the Action/Properties Panel.

#### Expected Experience: ####
The 'Action/Properties' Panel is non-transparent.

#### Actual Experience: ####
Part of the 'Action/Properties' Panel is transparent.
![image](https://user-images.githubusercontent.com/34729022/51018085-4c98fc80-15b1-11e9-8e3d-0ab80d3d4ad2.png)

**Comment by jinglouMSFT** [comment]
I can't repro this on the release bits of 1.6.2.  Is there anything specific i need to do to consistently repro this?  Also, what happens if you resize the panel? Thanks.

**Comment by v-xuanzh** [comment]
Hi @jinglouMSFT ，
1. This issue doesn't reproduce on the release build of 1.6.2. 
2. This issue still reproduces after resizing the panel.
3. This issue also reproduces on latest build 20190114.1.

**Comment by MRayermannMSFT** [comment]
Fix merged into master this morning.

**Comment by v-xuanzh** [comment]
This issue still reproduces on the latest build 20190115.1. So re-opened it.

**Comment by v-xianya** [comment]
Verified on build 20190115.6. This issue doesn't reproduce. Could you help to resolve it?

**Comment by jinglouMSFT** [comment]
Closing.
