### ISSUE TITLE
Fail to run the copied AzCopy command of downloading/uploading ADLS Gen2 blobs on CMD

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1079]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190116.1
**Commit:** ecdf6258
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Open one blob container then upload one file to it.
3. After uploading successfully, Click the link 'Copy AzCopy Command to Clipboard' next to the log message.
4. Download the latest azcopy from http://aka.ms/downloadazcopy-v10-windows -> Unzip it
5. Open CMD and change directory to 'azcopy_windows_amd64_10.0.5'.
6. Run the copied command: **azCopy.exe copy "C:\Program Files (x86)\Internet Explorer\*" "https://xuanadlsaccdemo.dfs.core.windows.net/ewewew/New Folder1/" --overwrite=false --follow-symlinks --recursive --fromTo=LocalBlobFS --list-of-files "C:\Users\vxuanzh\AppData\Local\Temp\stg-exp-azcopy-75542664-8adf-41d4-99f1-dba13901784c.json"**
7. Check the result.

#### Expected Experience: ####
Succeed to run the copied command on CMD.

#### Actual Experience: ####
Fail to run the copied command on CMD with the below error.
![error](https://user-images.githubusercontent.com/34729022/51367528-fdf5e000-1b25-11e9-8359-447c275f42e6.png)

**Comment by MRayermannMSFT** [comment]
The command assumes you have already set your account key as an environment variable, or that you have already signed into AzCopy. I'll work on adding these to the command that is copied to the clipboard.

**Comment by MRayermannMSFT** [comment]
Fix merged into master. Note that for Windows, commands are meant to be run in **Powershell**.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT , This issue still reproduces on the latest build 20190123.7. So reopened it(It seems like the order of the command is reversed)

Actually, we copied the AzCopy command to **notepad** like below when uploading/downloaging blobs.

![image](https://user-images.githubusercontent.com/34729022/51670746-4586db00-2002-11e9-8a08-8d9148c1a1b7.png)




But the same command shows like below after coping it to **PowerShell**.
![image](https://user-images.githubusercontent.com/34729022/51670797-64856d00-2002-11e9-8a67-e4ea04f19052.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh was using right click to paste into powershell. Hence the issue. :P
