### ISSUE TITLE
Show a confusing message when configuring soft delete policy for blob containers

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1293]
**Storage Explorer Version:** 1.7.0_20190416.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** c684556c
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a non-ADLS Gen2 account.
2. Right click on Blob Containers node -> Select 'Configure Soft Delete Policy...'.
3. Check the Activities.

**Expect Experience:**
Show a specific message which is configured for blob containers. 

**Actual Experience:**
The current message seems to express that soft delete policy is configured for one account.
![image](https://user-images.githubusercontent.com/41351993/56190516-eebafb80-605c-11e9-9b4b-d6584c7f1755.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into rel branch

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT  Verified on build 20190429.3. For this issue, the updated messages in Activities still not show the specific object(blob container) which is configured the soft delete policy. so we re-open it.

![image](https://user-images.githubusercontent.com/41351993/56938375-1ec1ce80-6b34-11e9-8fd9-ce7747938d6c.png)

**Comment by MRayermannMSFT** [comment]
Soft delete policy is set at the service level, so we show the name of the Storage Account. This is the same behavior as 1.7.0.

![image](https://user-images.githubusercontent.com/21112697/56976873-c76a3100-6b28-11e9-9b68-3f3549fca82f.png)
