### ISSUE TITLE
Unable to cancel queued transfers

### ISSUE THREAD

**Issue by dougjr17** [microsoft/AzureStorageExplorer#1306]
**Storage Explorer Version**: 1.7.2
**Platform/OS**: Windows 10?
**Architecture**: x64
**Regression From**: Unknown
**Bug description**
When you queue multiple files to transfer (upload from local storage to Azure) into blob in a blob container by selecting one file at a time, the transfers queue and wait until the currently transferring file completes. There is no CANCEL/ABORT option for these queued transfers. **Steps to Reproduce**
1. Upload a relatively large file to blob container (200MB+)
2. Before upload finishes click upload again and select another large file 
3. Again, click upload and select a third large file to upload into same blob container.
4. Try to cancel any of the queued files awaiting completion of the first file to begin uploading.

**Expected Experience**
Once a file is added to queue it should also be easily canceled/removed from queue before it begins transferring.

**Actual Experience**
Cancel transfer button only becomes available once queued transfer begins to actually actively transfer. You will not find a way to cancel a queued upload transfer before it begins transferring.

**Additional Context**
Using Office 365 PST Import SAS URI.
![AZStorageExplorerBUG](https://user-images.githubusercontent.com/29209519/56349084-d69ac780-6195-11e9-887c-6fb31c90228a.jpg)

**Comment by craxal** [comment]
Agreed, we should fix this.

**Comment by jrauschenbusch** [comment]
+1 Plz fix it asap

**Comment by cdeil** [comment]
I have a very large queued transfer, which for unknown reasons never started.
Now I cannot continue to download files with storage explorer because other download requests all get queued after this non-starting queued transfer.

Is there a workaround to this issue?

Can you please make this issue a priority?

**Comment by craxal** [comment]
@jrauschenbusch @cdeil The current status of the bug is "Under Review", which means there's a pull request with a fix we're looking over. Once completed, you can expect a fix to be available in the next release or two.

While you're waiting, the best bet is to restart Storage Explorer to clear out the job queue. Also, make sure you're running the latest version and that AzCopy transfers are turned on.

**Comment by notyourninja** [comment]
bump for for this feature request

**Comment by JasonYeMSFT** [comment]
I have merged the work to enable queued (but not started) AzCopy jobs. This will be included in the 1.20.0 release.

**Comment by soulexistence** [comment]
Using v1.36.2, this feature still isn't available, or was it removed?
![Image](https://github.com/user-attachments/assets/7b5fcd57-c054-402d-9f8e-ee550d7ed243)

**Comment by JasonYeMSFT** [comment]
My work was for cancelling normal queued AzCopy jobs (e.g. blob/file copy/upload/download). We have a work item planned for 1.37.0 to achieve this for Disk jobs. https://github.com/microsoft/AzureStorageExplorer/issues/7988

**Comment by soulexistence** [comment]
> My work was for cancelling normal queued AzCopy jobs (e.g. blob/file copy/upload/download). We have a work item planned for 1.37.0 to achieve this for Disk jobs. [#7988](https://github.com/microsoft/AzureStorageExplorer/issues/7988)

Good to know, thank you.
