### ISSUE TITLE
The opened editor isn't closed after deleting the new created ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1414]
**Storage Explorer Version:** 1.8.1_20190524.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Create a new blob container -> Make sure it has been opened automatically.
3. Try to delete the new created blob container on the tree view.
4. Check whether the opened editor is closed or not.

**Expect Experience:**

The opened editor is closed automatically.

**Actual Experience:**

The opened editor isn't closed.

**More info:**

This issue doesn't reproduce for one existing ADLS Gen2 blob container.

**Comment by craxal** [comment]
Reproducible on master branch.

**Comment by v-xuanzh** [comment]
Verified latest master build, This issue also reproduces for one normal new blob container.

**Comment by MRayermannMSFT** [comment]
Fix merged to master.

**Comment by v-xuanzh** [comment]
This issue still reproduces on latest  master build. 
Keep closed status. And we will verify it in next build.
