### ISSUE TITLE
An extra 'Detach' action shows for '(Emulator - Default Ports) (Key)' node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1617]
**Storage Explorer Version:** 1.9.0
**Build:** 20190806.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Lauch storage explorer 
2. Expand '**Local & Attached**' -> '**Storage Accounts**'
3. Right click '**(Emulator - Default Ports) (Key)**' node -> Check its context menu.

**Expect Experience:**
There is no 'Detach' for '(Emulator - Default Ports) (Key)' node.
![image](https://user-images.githubusercontent.com/41351993/62607950-88baf280-b931-11e9-8796-f8c7ce524438.png)

**Actual Experience:**
There shows an extra 'Detach' action for '(Emulator - Default Ports) (Key)' node.
![image](https://user-images.githubusercontent.com/41351993/62607829-501b1900-b931-11e9-8c40-1858f008cfb6.png)

**More info:**
It only refreshes the 'Storage Accounts' node after executing the detach action for the '(Emulator - Default Ports) (Key)' node.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
This isue still reproduces on the latest master build  20190813.12. So reopened it.

**Comment by MRayermannMSFT** [comment]
I think this was still repro'ing due to a bad CE commit. @v-xianya can you check for repro on tonight's build? Thanks.
