### ISSUE TITLE
The blob container auto refreshes with the option 'Auto-refresh blob editor' unchecked on Setting Panel

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1728]
**Storage Explorer Version:** 1.10.0
**Build:** 20190827.12
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings Panel -> Go to 'Data Explorer' tab -> Unchecked the the option 'Auto-refresh blob editor'.
3. Open one blob container -> Try to upload one blob to it.
4. Check whether the blob container auto refreshes or not.

**Expect Experience:**

1. The prompt for refreshing shows up.
2. The bob container doesn't automatically refresh.

**Actual Experience:**

1. The prompt for refreshing doesn't show.
2. The bob container automatically refreshes.

**Comment by MRayermannMSFT** [comment]
Fix merged into master

**Comment by v-xianya** [comment]
This issue still reproduces when uploading blobs with AzCopy unchecked. So we re-open it.
Releated bug: [916](https://github.com/Microsoft/AzureStorageExplorer/issues/916)

**Comment by JasonYeMSFT** [comment]
This is because classic upload doesn't implement this mechanism. Since it will be deprecated and replaced by AzCopy in the next release, we are not going to fix this. Could you please focus on testing the behavior when AzCopy is enabled? Thanks.
