### ISSUE TITLE
The uploading message shows as 'Uploading ... to ...' rather than 'Transferring ... to ...' when creating a disk

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1757]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure AzCopy is enabled.
2. Expand 'Disks' node -> Open one resource group.
3. Create a new disk from a local VHD file -> Check the uploading message on Activities.

**Expect Experience:**

The uploading message shows as 'Transferring ... to ...'.

**Actual Experience:**

The uploading message shows as 'Uploading ... to ...'.
![image](https://user-images.githubusercontent.com/34729022/64105832-89686c80-cda9-11e9-8dec-9a79746ed74e.png)

**More info:**

This issue also reproduces when uploading one disk.

**Comment by JasonYeMSFT** [comment]
This has been fixed in our latest build.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
This issue still reproduces on the lastest build 20200204.4.
So re-open it.
![image](https://user-images.githubusercontent.com/41351993/73715458-f7e19a00-474e-11ea-8d2b-47ce78b1ab7f.png)

**Comment by MRayermannMSFT** [comment]
Won't fix.
