### ISSUE TITLE
Add the sign 'ADLS Gen2' for an Azure AD attached ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1861]
**Storage Explorer Version:** 1.10.0
**Build:** [20190916.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3055553)
**Branch:** master
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Give an RBAC role to a user like 'Blob Data Owner Role' on one (ADLS Gen2) blob container tier.
2. Copy the URL of the ADLS Gen2 blob container -> Open Connect dialog -> Select 'Add a resource via Azure Directory(Azure AD)' -> 'Next'.
3. On the second page, choose the account with access to the ADLS Gen2 blob container .
4. On the third page, select Blob Contaiener(ADLS Gen2) as Resource type ->Paste the URL ->'Next'.
5. Check the attached blob container.

**Actual Experience:**
The attached blob container displays '[blob container name] (Azure AD - account)'.
![image](https://user-images.githubusercontent.com/41351993/65032346-8e1a4c80-d975-11e9-9781-0ac84f9f64a9.png)

**Suggestion:**
The attached blob container displays '[blob container name] **(ADLS Gen2)** (Azure AD - account)'.

**Comment by craxal** [comment]
These status messages are getting pretty long, to the point that they don't easily convey information anymore.

@jinglouMSFT Since we're starting work on interop, will we still need to differentiate ADLS Gen 2 blob accounts from regular ones?

**Comment by jinglouMSFT** [comment]
@craxal interop really means the two will share one set of APIs.  The user experiences probably will like be the same as today. For a better support experience, it's probably easier to still have the label for ADLS Gen2.  That way, if something goes wrong, our CSS engineers or us will not have to go back and forth asking if it's the regular blob or ADLS Gen2.   Plus this should be a fairly easy fix.  We already have the information. We just need to show it in the message.

**Comment by craxal** [comment]
What if we did one of the following?

> 📈 **testnewblob** (ADLS Gen 2 | Azure AD - v-zhiyul@microsoft.com)
> 📈 **testnewblob** | ADLS Gen 2 | Azure AD - v-zhiyul@microsoft.com |
> 📈 testnewblob _| ADLS Gen 2 | Azure AD - v-zhiyul@microsoft.com |_

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
This issue still reproduces on build 20191009.1. So we re-open it.

**Comment by MRayermannMSFT** [comment]
Sorry. We didn't update the cloud explorer reference. You should see it in tonight's build.
