### ISSUE TITLE
The strings in 'Connect Summary' dialog are not translated completely

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1929]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW)/ Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command `StorageExplorer.exe --lang=zh-CN`.
2. Select one storage account -> Copy its 'Primary Key'.
3. Open connect dialog -> Select 'Using a storage account name and key' -> Next.
4. Paste the 'Primary Key' and input Display name and Account name -> Next.
5. Check the Connect Summary dialog.

**Expect Experience:**
The stings are translated completely.

**Actual Experience:**
The stings are not translated completely.
![image](https://user-images.githubusercontent.com/41351993/65682339-5f932480-e08d-11e9-85bd-9ea61a9c293b.png)

**More Info:**
This issue reproduces for 'Connect Summary' dialogs using SAS attached.

**Comment by craxal** [comment]
Hard-coded string. Good catch!

**Comment by craxal** [comment]
The summary is now fixed. We will fix the title bar localization for a later release, so I will close this issue as resolved.

**Comment by v-limu** [comment]
The 'Back' & 'Cancel' buttons are not localized in **Chinese(zh-CN) / Chinese(zh-TW) / Korean / Japanese / German** with build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616). So we reopen it.

**Comment by v-limu** [comment]
Hi @lukaschal Verified on build[ 20200327.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3588105). This issue still reproduces. 
![image](https://user-images.githubusercontent.com/54055206/77732961-f773ca00-7040-11ea-90ac-ed2503df4c00.png)

**Comment by lukaschal** [comment]
@craxal Are these buttons exposed to localization ?

**Comment by craxal** [comment]
@lukaschal I labeled this issue with "hard-coded string", so no, they aren't exposed to localization yet. Once they're localized, we'll change the status of this bug to "Translating", so you can know when to expect the string.

**Comment by craxal** [comment]
@v-limu I'm creating a new issue #2770 for the unlocalized buttons, because the original issue here was resolved quite some time ago for 1.11.0.
