### ISSUE TITLE
Add 'Details…' append to the deletion log of one blob with snapshots

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2202]
**Storage Explorer Version:** 1.11.0
**Build:** [20191102.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3207164)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container which contains one blob at least.
3. Select one blob and create snapshots for it.
4. Delete the blob then check the log message.

**Expect Experience:**
1. Show 'Details...' append to the deletion log message.
![image](https://user-images.githubusercontent.com/41351993/68112697-de04a100-ff2c-11e9-8539-c4c295ea0615.png)

2. Click 'Details...' could get an exact message (Like: because the blob has snapshots)

**Actual Experience:**
No 'Details...' append to the deletion log message.
![image](https://user-images.githubusercontent.com/41351993/68112139-a8ab8380-ff2b-11e9-9422-0eda293a85b4.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-limu** [comment]
Verified on build 20200303.6. This issue still reproduces. So we reopen it.
![image](https://user-images.githubusercontent.com/54055206/75763905-f9b37300-5d77-11ea-846e-79f93b16b88f.png)

**Comment by JasonYeMSFT** [comment]
I have published a new package for this fix. Please verify.

**Comment by v-xianya** [comment]
Verified this issue on build [20200304.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3522896&view=results). Fixed.
