### ISSUE TITLE
Disks is localized in path of one opened resource group

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2328]
**Storage Explorer Version:** 1.11.0
**Build:** [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921&view=results)
**Branch:** master
**Language:** Chinese(zh-CN) / Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand Disks -> Open one resource group.
4. Hover the mouse to the opened resource group tab.
5. Observe the shown path.

**Expect Experience:**
Disks is not localized.

**Actual Experience:**
Disks is localized.
![image](https://user-images.githubusercontent.com/41351993/69613702-dd6ca100-0fe6-11ea-9cd4-010eca1b5c13.png)

**Comment by lukaschal** [comment]
File: loc\en\src\components\se-managed-disks-extension\resources\ManagedDisks.json
ID: 0; "Disks"
SRC: Disks
TGT: 磁盘

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "TitleDisks"
SRC: Disks
TGT: 磁盘

**Comment by lukaschal** [comment]
@v-xianya Please is it possible provide ENU screenshot ?

**Comment by v-xianya** [comment]
@lukaschal     
  ENU screenshot
![image](https://user-images.githubusercontent.com/41351993/69686131-924c9f80-1073-11ea-80e0-068d210238e6.png)

**Comment by lukaschal** [comment]
On review.

**Comment by v-xianya** [comment]
@lukaschal 

1. This issue is fixed in zh-CN.
![image](https://user-images.githubusercontent.com/41351993/70211122-539f9f00-176f-11ea-822b-7768e1c435e7.png)

2. This issue still reproduces in zh-TW.
![image](https://user-images.githubusercontent.com/41351993/70210917-cf4d1c00-176e-11ea-86d4-e9a1ac0271c3.png)

**Comment by lukaschal** [comment]
Unlocalized on all languages except RUS.

**Comment by craxal** [comment]
Verified fixed in master.

**Comment by v-xianya** [comment]
Verified on the latest build master/ [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517&view=results)
This issue still reproduces in Chinese(zh-TW). So we re-open it.
![image](https://user-images.githubusercontent.com/41351993/70701925-2cfddd00-1d08-11ea-8b2c-61bf8c8ed715.png)

**Comment by lukaschal** [comment]
Both standalone instances "Disks" on zh-tw are unlocalized in a loc repository.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hant%2Fsrc%2FStandalone%2Fresources%2FShell.json.lcl&version=GBmaster

      <Item ItemId=";TitleDisks" ItemType="0" PsrId="306" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Disks]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Disks]]></Val>
          </Tgt>

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hant%2Fsrc%2Fcomponents%2Fse-managed-disks-extension%2Fresources%2FManagedDisks.json.lcl&version=GBmaster&_a=contents

      <Item ItemId=";Disks" ItemType="0" PsrId="306" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Disks]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Disks]]></Val>
          </Tgt>

**Comment by MRayermannMSFT** [comment]
Verified.
