### ISSUE TITLE
The translation of the second option string is incorrect in 'File Changes Detected' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2420]
**Storage Explorer Version:** 1.11.1
**Build:** [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517&view=results)
**Branch:** master
**Language:** Chinese(zh-CN)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one non-ADLS Gen2 storage account -> Blob Containers.
4. Create a blob container -> Upload a text file.
5. Open this file then make some changes -> Save the file.
6. Check the translation of the second option string in the prompt dialog.

**Expect Experience:**
The translation of the second option string is correct.
Like: （创建原始blob的快照然后上传）

**Actual Experience:**
The translation of the second option string is incorrect.
![image](https://user-images.githubusercontent.com/41351993/70697687-f2dd0d00-1d00-11ea-890d-a07aa7121be4.png)

**More Info:**
1. It is better to translate **Upload** to '上传' instead of '上载' in **zh-CN**.
![image](https://user-images.githubusercontent.com/41351993/70699724-89f79400-1d04-11ea-9984-f089667c59f5.png)

2. ENU screenshot.
![image](https://user-images.githubusercontent.com/41351993/70699134-9f1ff300-1d03-11ea-8aae-00bc03e42b55.png)

3. zh-TW screenshot.
![image](https://user-images.githubusercontent.com/41351993/70699176-afd06900-1d03-11ea-83dc-d23aa28b3586.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "OptionFileWatcherSnapshotUpload"
SRC: Snapshot original blob then upload
TGT: 然后上载快照原始 blob

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "OptionFileWatcherUpload"
SRC: Upload
TGT: 上载

**Comment by lukaschal** [comment]
Fixed.

SRC: Snapshot original blob then upload
New TGT: 然后上传快照原始 blob

SRC: Upload
New TGT: 上传

**Comment by v-xianya** [comment]
@lukaschal 
Translate the option 'Snapshot original blob then upload' to '创建原始blob的快照然后上传' would be better.
![image](https://user-images.githubusercontent.com/41351993/74902285-88230e80-53e0-11ea-8d04-cd3ddeec09a6.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "OptionFileWatcherSnapshotUpload"
SRC: Snapshot original blob then upload
TGT: 然后上传快照原始 blob

**Comment by lukaschal** [comment]
Fixed.

new tgt: 创建原始 blob 的快照然后上传

**Comment by v-xianya** [comment]
@lukaschal 
This issue still reproduces on build [20200226.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3502854).

**Comment by jinglouMSFT** [comment]
This has been fixed and verified in build 20200228.1.  Here is a screenshot:

![image](https://user-images.githubusercontent.com/10081483/75503162-c04ec200-5989-11ea-9f05-e2d18db334e6.png)

Feel free to close.

**Comment by v-xianya** [comment]
@jinglouMSFT Thank you very much for helping to verify this bug. We will close it.
