### ISSUE TITLE
Update 'ADLS Gen 2' to 'ADLS Gen2' in Settings AzCopy part with German

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2497]
**Storage Explorer Version:** 1.11.2
**Build**: [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: German
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsche' -> Restart Storage Explorer.
3. Open Settings -> Transfer -> AzCopy.
4.  Check the first sentence.

**Expect Experience:**
Show 'ADLS Gen2' in the sentence.

**Actual Experience:**
Show 'ADLS Gen 2' in the sentence.
![image](https://user-images.githubusercontent.com/54055206/71470004-d3b4a400-2805-11ea-9d87-44bd59775c9c.png)

**Comment by johnliu2016** [comment]
Sending to localization team for review

**Comment by lukaschal** [comment]
Fixed.

File: loc\en\src\components\se-az-copy-extension\resources\AzCopySettings.json
ID: 0; "DescriptionAzCopy"
SRC: Use these settings to tune the performance of AzCopy. AzCopy is used for Blobs, ADLS Gen2 and Managed Disks.
TGT: Verwenden Sie diese Einstellungen, um die Leistung von AzCopy zu optimieren. AzCopy wird für Blobs, ADLS Gen2 und Managed Disks verwendet.

**Comment by v-limu** [comment]
This issue also reproduces in **Spanish**.
![image](https://user-images.githubusercontent.com/54055206/72588198-832af500-3932-11ea-8e29-86270ea3bb4e.png)

**Comment by johnliu2016** [comment]
Fixed in Spanish. Please verify for new build.

**Comment by JasonYeMSFT** [comment]
Verified as fixed.

**Comment by v-limu** [comment]
Verified on build [20200118.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3397152). This issue still reproduces in **Spanish**. So we reopen it.
![image](https://user-images.githubusercontent.com/54055206/72677349-7a732400-3ad6-11ea-9259-9e9859457fbc.png)

**Comment by lukaschal** [comment]
Checked in at 1/17/2020.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/982a46c90db096aa24cdc78fcf147cb6df0cea1b?_a=compare&path=%2Floc%2Floc%2Fes%2Fsrc%2Fcomponents%2Fse-az-copy-extension%2Fresources%2FAzCopySettings.json.lcl

**Comment by lukaschal** [comment]
@v-limu Should be fixed on latest build. Please confirm.

**Comment by v-limu** [comment]
Verified on build [20200201.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3434212&view=results). This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/73625996-18e5a600-45fc-11ea-931c-ee94b489c3a5.png)
