### ISSUE TITLE
The localized 'Expiration Time' is different between the queue editor and View Message dialog 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2568]
**Storage Explorer Version:** 1.12.0
**Build**: [20200122.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3404394)
**Branch**: master
**Language:** Italian / Turkish
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Italiano**' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Create a new queue -> Add massage - > View this message.
5. Check the localized 'Expiration Time' in the queue editor and view message dialog.

**Expect Experience:**
The localized 'Expiration Time' keeps consistent.

**Actual Experience:**
The localized 'Expiration Time' is different.
![image](https://user-images.githubusercontent.com/54055206/72880340-b22dd600-3d39-11ea-89de-3196101b6b72.png)

**More Info:**
This issue also reproduces for the localized 'Message Text'.

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

**Comment by v-limu** [comment]
Verified on build [20200201.2.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3434212&view=results) This issue still reproduces.

**Comment by lukaschal** [comment]
@v-limu Screen is same as above, or there are some differencies ?

**Comment by v-limu** [comment]
Hi @lukaschal 

ENU screenshot: The queue editor and view message dialog are same.
![image](https://user-images.githubusercontent.com/54055206/74410250-a6828a80-4e73-11ea-9122-d7443b41f55e.png)

**Comment by lukaschal** [comment]
@v-limu And what is wrong on italian for now ?

**Comment by v-limu** [comment]
Hi @lukaschal 
The localized 'Message Text' & 'Expiration Time' & 'Insertion Time' are different between the queue editor and View Message dialog
![image](https://user-images.githubusercontent.com/54055206/74427284-c0cb6100-4e91-11ea-868d-02bef6f1de01.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed now.

**Comment by v-xianya** [comment]
Hi @lukaschal 
Verified on buid 20200219.2.  
1. This issue also reproduces for 'Insertion time' in **Italian**.
![image](https://user-images.githubusercontent.com/41351993/74807555-b7277a80-5323-11ea-85a1-5cb569ae4f39.png)
2. This issue also reproduces for 'Insertion time' & 'Expiration time' in **Turkish**.
![image](https://user-images.githubusercontent.com/41351993/74808305-86e0db80-5325-11ea-8f59-6c4a1fee7c7b.png)

**Comment by lukaschal** [comment]
@v-xianya Please verify on some latest build from 2/25 or later.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/ecf4be619b7835009d2dc5e1d1cc7602156586c5?_a=compare&path=%2Floc%2Floc%2Fit%2Fsrc%2Fcomponents%2Fse-queue-extension%2Fresources%2FQueueEditor.json.lcl

**Comment by v-xianya** [comment]
Verified this issue on build [20200225.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3498630). 
1. Fixed in Italian.
2. Reproduces in Trukish.

**Comment by lukaschal** [comment]
TRK fixed as well.

**Comment by v-xianya** [comment]
Verifed on build [20200227.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3506444&view=results). Fixed.
