### ISSUE TITLE
Miss a quantifier in the localized blobs deletion activity log 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2653]
**Storage Explorer Version:** 1.12.0
**Build**: [20200220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3486308)
**Branch**: master
**Language:** Chinese (zh-CN)
**Platform/OS:** Windows 10/ CentOS Linux release 7.6.1810(Core)
**Architecture:** ia32/x64
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**中文（简体）**' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Select one blob container which contains one blob at least -> Select one blob then delete it.
5. Check the activity log.

**Expect Experience:**
Display a quantifier in the activity log.

**Actual Experience:**
No quantifier shows in the localized activity log.
![image](https://user-images.githubusercontent.com/41351993/74930198-08189b00-5418-11ea-9572-3ca14c76b14a.png)

**More Info:**
 1. This issue doesn't reproduce in Chinese (zh-TW).
![image](https://user-images.githubusercontent.com/41351993/74930233-1e265b80-5418-11ea-9f1f-cb235b3a24b9.png)
2. This issue also reproduces when deleting files under one file share.

3. ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/74930248-22eb0f80-5418-11ea-9f89-476288b6c8a2.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-az-copy-extension\resources\Delete.json
ID: 0; "ItemDeleted"
SRC: %1$s completed
TGT: %1$s 已完成

**Comment by lukaschal** [comment]
Fixed.

new tgt: %1$s 个已完成

**Comment by v-xianya** [comment]
@lukaschal This issue still reproduces on build [20200226.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3502854).

**Comment by v-xianya** [comment]
Fixed on build [20200228.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3510155). So we close this issue.
