### ISSUE TITLE
 Auto open new tabs when clicking one opened queue under Quick Access

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3002]
**Storage Explorer Version:** 1.14.0-dev
**Build**:[ 20200519.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3738672)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Select one queue and add it to Quick Access.
3. Open the queue under QA -> Click the queue multiple times.
4. Check whether the queue auto open new tabs or not.

**Expect Experience:**
No new tabs opened.
![image](https://user-images.githubusercontent.com/54055206/82307157-8c1bf800-99f2-11ea-88c3-8b3dec0cc65b.png)

**Actual Experience:**
Auto open new tabs.
![image](https://user-images.githubusercontent.com/54055206/82308434-5d068600-99f4-11ea-856b-7592df5ebd89.png)

**More Info:**
This issue doesn't reproduce for one file share / table / blob container.

**Comment by craxal** [comment]
@v-limu I am unable to reproduce this issue. Possibly fixed in a package update that's not yet merged.

Just to be sure, how fast are you clicking on the node? You're not double-clicking, are you?

**Comment by v-limu** [comment]
Hi @craxal 
Verified on build [20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results). This issue still reproduces on click or double-click. Please see the record:
https://web.microsoftstream.com/video/e9faa0ff-0400-96d0-1fe9-f1ea9a43841a

**Comment by v-limu** [comment]
Verified on build 20200602.3. This issue has been fixed. So close it.

**Comment by craxal** [comment]
Reopened, because this fix also relies on an update to the queue extension package and needs verification against that.

**Comment by v-limu** [comment]
Verified on build 20200616.5. This issue reproduces. So reopen it.

**Comment by craxal** [comment]
@v-limu I am unable to reproduce the issue using the same build. Can you provide more precise repro steps?

**Comment by v-limu** [comment]
Hi @craxal  Sorry for the above comments. Verified on build 20200617.5. This issue also reproduces. The steps as below.😃

**Repro Steps:**
1. Expand one storage account -> Queues.
2. Open one queue (Click 'Open' on the queue's context menu).
3. **Double-click** the queue using mouse on the tree view.
4. Check the tabs.

**More Info:**
This issue also reproduces under Quick Access.

**Comment by craxal** [comment]
@v-limu This is by design. A double-click is intended to open a new tab regardless of whether there's already a tab open. This is the same behavior for other node types.

**Comment by v-limu** [comment]
Hi @craxal  Thanks for your updates. 

But, only one tab always displays when I double-click one **blob container / file share / table** (regardless of whether there is already a tab open). This behavior is different from queues.

**Comment by craxal** [comment]
@v-limu My mistake, double-click is supposed to open a permanent tab, not a new tab. I'll get this fixed.
