### ISSUE TITLE
Fail to rename the blob when entering a name contains " ' "

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#3360]
**Storage Explorer Version:** 1.15.0-dev
**Build:** 20200806.6
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one blob -> Right click the blob -> Select 'Rename...' -> Enter "test'1".
3. Check the result.

**Expect Experience:**
Succeed to rename the blob.

**Actual Experience:**
Fail to rename the blob when entering a name "test'1".
![image](https://user-images.githubusercontent.com/57662131/89517094-d3ed3700-d80b-11ea-8ed9-598f2185c439.png)

**More Info:**
This issue doesn't reproduce on File Shares and regular Blob Containers.

**Comment by MRayermannMSFT** [comment]
@v-xinda can you still repro this? We're having a hard time doing so. Also, can you share with us the error details?

**Comment by v-xinda** [comment]
Hi @MRayermannMSFT  
This issue also reproduces on the build 20200811.2. Error details as below.
Error Details:
```
{
 "name": "Error",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:16f44a82-701f-00ab-6683-6fe84a000000\nTime:2020-08-11T02:04:13.4702143Z",
  "stack": "Error: This request is not authorized to perform this operation using this permission.\nRequestId:16f44a82-701f-00ab-6683-6fe84a000000\nTime:2020-08-11T02:04:13.4702143Z\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2400:28)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3544:37\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403
}
```

**Comment by JasonYeMSFT** [comment]
@v-xinda The error message says the failure is due to missing permission. For rename (move) in ADLS Gen2, you will see such error details if you miss the "write" permission on the directory you are moving you blob into.

However, this doesn't seem to be the case. According to the issue description, you can upload a blob into the directory, meaning that you have "write" permission on that directory. Could you please make sure you try this with the write permission and see if the issue still reproduces?

**Comment by v-xinda** [comment]
@JasonYeMSFT  Hi
Verified this issue on build master/20200818.4. Still reproduces.
More details please see the record: [https://msit.microsoftstream.com/video/5517a1ff-0400-8385-52b4-f1eae0fd4a23](https://msit.microsoftstream.com/video/5517a1ff-0400-8385-52b4-f1eae0fd4a23)

**Comment by JasonYeMSFT** [comment]
I still cannot reproduce the issue. Renaming a blob with name containing single quote ' just works fine.
![image](https://user-images.githubusercontent.com/39359541/94975999-57539d80-04c8-11eb-8268-6d3070d21b46.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT  

Verified this issue on build 20201010.6 and 1.15.1 release. Reproduce.
![image](https://user-images.githubusercontent.com/41351993/95729951-2e918c00-0cb0-11eb-88ba-75ab4fa06401.png)

**Comment by JasonYeMSFT** [comment]
I managed to reproduce this issue. It only occurs when we use account name and key to authorize the rename action.

**Comment by MRayermannMSFT** [comment]
Jason, please open an issue against the SDK, and then move this to 1.18.

**Comment by JasonYeMSFT** [comment]
The issue is in the preview SDK and won't get fixed there. We need to upgrade to the public SDK to fix this issue.

**Comment by JasonYeMSFT** [comment]
A blocking issues in the public SDK has been fixed here https://github.com/Azure/azure-sdk-for-js/issues/11849.

**Comment by JasonYeMSFT** [comment]
I just verified it today and it seems to have been fixed by integrating the new SDK.

**Comment by sid5233** [comment]
I'm still facing this issue. If I add my public IP address only then I'm able to rename the blob.

**Comment by JasonYeMSFT** [comment]
@sid5233 Could you open a new issue describing what you see? The original issue doesn't have anything to do with IP address. If you have a firewall setting, you are expected to add your IP in the rules.
