### ISSUE TITLE
Show a folder named '&amp;' after creating a folder with the name '&'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3377]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200811.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'New Folder' -> Input '&' as the new folder name -> Click 'OK'.
3. Check the result.

**Expect Experience:**
Show a folder named '&'.
![image](https://user-images.githubusercontent.com/41351993/89873960-c6f68c00-dbed-11ea-8158-dfc68b3c306a.png)

**Actual Experience:**
Show a folder named![image](https://user-images.githubusercontent.com/41351993/89875098-610b0400-dbef-11ea-98b0-ec056da1465f.png).

![image](https://user-images.githubusercontent.com/41351993/89873951-c2ca6e80-dbed-11ea-805b-05281f562aad.png)

**More Info:**
1. Show '&' on the path.
2. Show blank under the 'Recent locations' dropdown list.
![image](https://user-images.githubusercontent.com/41351993/89874442-6d429180-dbee-11ea-847c-f314fe0953ca.png)
3. This issue doesn't reproduce for ADLS Gen2 blob containers.

**Comment by craxal** [comment]
The menu problem looks like an Electron bug/missing feature. The ampersand is stripped out and interpreted as a keyboard accelerator. I've opened electron/electron#25028.

The "&amp;" is the result of encoding done when displaying the folder name in the data table. The data itself is correct (verified in the portal), but I'm not sure why this has changed (since I don't see any relevant changes in that part of the code.

**Comment by v-limu** [comment]
Verified on build 20201126.1. This issue doesn't reproduce. So we close it.

**Comment by craxal** [comment]
@v-limu The Electron bug is still open. Is the Recent Locations menu part still an issue? If so, please reopen this bug so we can track.

**Comment by v-limu** [comment]
Hi @craxal Got it. Thanks for your update. This issue is re-opened now.

**Comment by craxal** [comment]
@v-limu Can you help create a separate issue for the menu item? The `&amp;` issue should be fixed, but the menu item is a separate issue.

**Comment by v-limu** [comment]
Hi @craxal The Recent Locations menu part still an issue. So we logged a new bug for the menu item. [3955](https://github.com/microsoft/AzureStorageExplorer/issues/3955)
