### ISSUE TITLE
Cannot open blob container or datalake

### ISSUE THREAD

**Issue by crisar19** [microsoft/AzureStorageExplorer#3633]
**Storage Explorer Version**: 1.15.1 
**Build Number**: 20200902.9
**Platform/OS**: Windows
**Architecture**: ia32 (I took it from Help > About)
**Regression From**:  yes, in the same version

## Bug Description ##

at the moment to open a blob container or datalake I get this message:

this when trying to open datalake :unable to get local issuer certificate

this when trying to open blob container: 
Unable to retrieve child resources.

Details:
["FetchError:request to https://azsaprccp002.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate"]

## Steps to Reproduce ##

open a blob container and i get this message directly

## Expected Experience ##

If I open a blob container, allow me to do it and see all the information that I have

**Comment by MRayermannMSFT** [comment]
Please see our troubleshooting guide on cert errors: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by shali-sly5** [comment]
I have encountered the same issue above. Can you please let me know how you resolved this issue?

**Comment by crisar19** [comment]
Hi,

I found out that issue is coming from my company network. They implemented a new security protocol, where bassically they block some websites as malicious URL.


Also I tried to include the SSL certificates (look the link above) but still not working

**Comment by MRayermannMSFT** [comment]
@crisar19 did you convert the certs to base64 encoded as described in the link?

**Comment by crisar19** [comment]
@MRayermannMSFT hi,

Yes I did it, but the issue is from my company network. When I work from home I don't have any issues on it. Right now they solve the Blob containers access, but now still having issues with Datalake storage access.

Thanks for your info

**Comment by MRayermannMSFT** [comment]
@crisar19 when you say "they solve the Blob containers access, but now still having issues with Datalake storage access" do you mean that after adding the certs, you were able to access your blobs but not your datalake?

What datalake version are you using? Gen1 or Gen2? Or in other words, this is Gen1:
![image](https://user-images.githubusercontent.com/21112697/96494109-bfa9bb00-11fa-11eb-824f-4a90822a1d1b.png)

And this is Gen2:
![image](https://user-images.githubusercontent.com/21112697/96494020-a0ab2900-11fa-11eb-8852-f1dd0988f5d6.png)

Which are you using?

**Comment by crisar19** [comment]
@MRayermannMSFT I'm using datalake Gen1. Now this is solved. In the first fix they only included blobs, but now they fix DataLake Gen1 too.

Thanks for your replies, I really appreciate it

**Comment by shali-sly5** [comment]
I imported x509.js certificate but still getting the same issue "Unable to locate delete retention policy properties: unable to get local issuer certificate"

**Comment by MRayermannMSFT** [comment]
@shali-sly5 can you please open a new issue specific for your issue/scenario? Thanks!
