### ISSUE TITLE
The statistics are failed when using the action 'Selection Statistics 2' for one soft deleted blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3832]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201203.3
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers (Enable the Soft Delete Policy).
2. Create a new blob container -> Upload one blob then delete it.
3. Switch to 'Active and soft deleted blobs' view.
4. Right click the soft deleted blob -> Click 'Selection Statistics 2'.
5. Check whether the blob statistics are successful.

## Expected Experience ##
The blob statistics are successful.

## Actual Experience ##
The blob statistics are failed.
![image](https://user-images.githubusercontent.com/54055206/100987020-e8a6c500-3588-11eb-9eb8-cf61ccb930da.png)

Error details:
![image](https://user-images.githubusercontent.com/54055206/100987051-f2302d00-3588-11eb-8bc1-8c4e82037be8.png)

## Additional Context ##

1. This issue doesn't reproduce for one soft deleted folder.
2. This issue doesn't reproduce when executing the action 'Selection Statistics'.

**Comment by MRayermannMSFT** [comment]
Fix merged in build #20201204.3 and later.

**Comment by MRayermannMSFT** [comment]
@v-xianya and @v-limu , for this scenario, it is expected that "selections statistics 2" does **not** count a soft deleted blob towards the statistics. The statistics feature is supposed to only count **active** blobs. It should not count non-active blob versions, soft deleted blobs, and snapshots. The fact that the old statistics counts those is a bug.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on build 20201204.4. When performing 'selections statistics 2' for one soft deleted blob.
Still show a failed activity log. 
Could you to confirm whether it needs to be verified on a later build or there is a problem?
![image](https://user-images.githubusercontent.com/41351993/101150016-a8177c00-365a-11eb-844c-dcad25e81e73.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya the error is unintended. I'll fix that in next build.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201206.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/101316744-0da47c00-3898-11eb-9f1e-a9d27f126c0e.png)
