### ISSUE TITLE
Border should still be red after deleting incorrect strings from the 'Blob container SAS URL' field on the 'Enter Connection Info' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4332]
**Storage Explorer Version**: 1.19.0
**Build Number**: 20210414.2
**Branch**: rel/1.19.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.17.0)

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open the connect dialog -> Select 'Blob container -> Shared access signature URL (SAS)' -> Click 'Next'.
3. Type any strings to the 'Blob container SAS URL' field until an error message shows.
4. Delete all strings from the 'Blob container SAS URL' field -> Check whether the error message disappears.

## Expected Experience ##
The error message disappears.

## Actual Experience ##
The error message doesn't disappear.
![image](https://user-images.githubusercontent.com/41351993/114703652-25b16e00-9d58-11eb-89b6-2e759f13b116.png)

## Additional Context ##
This issue reproduces for the text fields on the 'Inter Connection Info' dialog.

**Comment by craxal** [comment]
@v-xianya I'm going to say this is by design. We only hide validation messages when the panel first appears. An empty field is invalid, so showing an error message after making changes to the field's value is appropriate.

**Comment by jinglouMSFT** [comment]
I respectfully disagree. This would be by-design only if we also display an error message after you have done step 2 and before step 3.  Otherwise the behavior is not consistent and shouldn't be by-design.

**Comment by v-limu** [comment]
Hi @craxal Verified on build main/20210426.5. This issue still reproduces. So we re-open it.
![image](https://user-images.githubusercontent.com/54055206/116192739-1da3e780-a6e3-11eb-90c6-5ac7b4d84c1f.png)

**Comment by craxal** [comment]
@v-limu @jinglouMSFT This should be by design. The expected behavior is not consistent with how we've been writing other dialogs. I don't think it makes sense to display no validation message after the user has made inputs when there is a validation problem.

**Comment by jinglouMSFT** [comment]
![forcraig (1)](https://user-images.githubusercontent.com/10081483/117382302-12934900-ae93-11eb-956c-ea4436aee245.gif)

Notice that when the dialog was launched, the border of the text control is in blue and there is no error message. 
Then after I've typed in the invalid SAS URL, the border switched to red and the error message appeared. I then went backspace to erase all the chars in the text control, the error message is still there but the border of the text control is switched back to blue, which indicated to me that the text control is NOT in an error state, which contraindicates to what you said that "empty string is an invalid input".  So we are sending a mixed message here.  The expected behavior should be either the control border to be red with the error message or get rid of the error message if leaving the border blue.  I prefer leaving the border blue as this was how our previous versions worked.  Don't know what the reason was when you changed the behavior.

**Comment by craxal** [comment]
OK, yes, _that_ is inconsistent, and we should fix that.

**Comment by v-limu** [comment]
Hi @craxal Verified on the lasted build 20210526.1. This issue still reproduces.

**Comment by craxal** [comment]
@v-limu The commit containing the fix for this got lost somehow. Please verify again.

**Comment by v-limu** [comment]
Hi @craxal We verified on the lasted build 20210526.8. This issue still reproduces.
The the control border is still blue.
![image](https://user-images.githubusercontent.com/54055206/119757029-f48b9800-bed6-11eb-9437-236bf75a93b5.png)

**Comment by craxal** [comment]
@v-limu OK, I'll take a look. If it reproduces, though, please reopen the issue.

**Comment by v-limu** [comment]
Hi @craxal In the 'Connect' dialog. No red border shows for below dialogs when there is an empty or invalid field.

- Subscription
Manage Custom environment -> 'Add Custom Environment' dialog

- Storage account or service
1. Connection string (Key or SAS)
2. Shared access signature URL (SAS)
3. Account name and key

- Blob container
1. Sign in using Active Directory (Azure AD)
2. Shared access signature URL (SAS)
3. Anonymously (my blob container allows public access)


- ADLS Gen2 container or directory
1. Sign in using Active Directory (Azure AD)
2. Shared access signature URL (SAS)
3. Anonymously (my blob container allows public access)

- File Share
- Queue
1. Sign in using Azure Active Directory (Azure AD)
2. Shared access signature URL (SAS)

- Table
- Local storage emulator
Enter Connection Info -> 'Display name' text box.

**Comment by v-limu** [comment]
Hi @craxal Verified on the build main/20210601.8.

1. This issue has been fixed for 'Subscription, Storage account or service, Blob container, ADLS Gen2 container or directory, File Share, Queue, Table' dialogs.
2. **But for the 'Local storage emulator'**. An incorrect red border shows for these test box 'Blobs port, Files port, Queues port, Tables port' when deleting its value. 
![image](https://user-images.githubusercontent.com/54055206/120433183-81d65d00-c3ad-11eb-8c4f-558394ededb5.png)
