### ISSUE TITLE
The current access tier is not localized in the "Update Access Tier" dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5106]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211029.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**Language:** All languages
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload one blob.
5. Right click the blob -> Click 'Change Access Tier...'.
6. Check whether the current access tier is localized in the dialog.

## Expected Experience ##
 The current access tier is localized.

## Actual Experience ##
 The current access tier is not localized.
![image](https://user-images.githubusercontent.com/87792676/139402732-d5426788-439a-49b8-b26d-4a72fec254bd.png)

**Comment by JasonYeMSFT** [comment]
We have locked down for 1.22.0 and loc strings needs to wait until 1.23.0.

**Comment by JasonYeMSFT** [comment]
Done localizing these strings for 1.23.0. Will be waiting for translations.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT, This issue still reproduces on the build main/20220206.3.

**Comment by v-xianya** [comment]
@JasonYeMSFT we are going to re-open this issue and keep eyes on this. Once it got fixed, will close it.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220212.2. Fixed. So close it.
