### ISSUE TITLE
The 'X' button is hard to see when searching by prefix in dark theme

### ISSUE THREAD

**Issue by v-haiz** [microsoft/AzureStorageExplorer#518]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Build Number**: 20180730.1
**Commit**: 17eb92a4
**Regression From**: Not a Regression

**Steps to Reproduce**:
1. Switch to dark theme and open a blob container/file share -> Input a prefix in search box.
2. Check whether the 'X' button is clear to see or not.

**Expected Experience**:
The 'X' button is clear to see.

**Actual Experience**:
The 'X' button is hard to see when searching by prefix.
![comparepre](https://user-images.githubusercontent.com/37653604/43452087-1968e410-94a6-11e8-868e-c4000463f598.PNG)

**Comment by MRayermannMSFT** [comment]
This is fixed. We updated the icon at some point.

**Comment by v-limu** [comment]
Verified on build [20200317.2](https://devdiv.visualstudio.com/devdiv/_build/results?buildid=3556898). This issue still reproduces. So we reopen it.
![image](https://user-images.githubusercontent.com/54055206/76830606-8eca6780-6860-11ea-8578-bf2a8cfa2f1c.png)

**Comment by craxal** [comment]
@v-limu The X in the lefthand side is different than the X on the righthand side. The righthand side X is actually controlled by the system. Here's what it looks like on macOS:

![image](https://user-images.githubusercontent.com/3473026/81873681-1b2b9a80-9531-11ea-8574-66021e545faf.png)

Unfortunately, that means we don't have control over its appearance.

@jinglouMSFT @MRayermannMSFT @JasonYeMSFT What are your thoughts? Should we try to fix this? A fix would involve modifying the UI to be similar to the lefthand side.

**Comment by jinglouMSFT** [comment]
@craxal the contrast between the X and the background of the search control on Windows in dark theme is not >70%.  If we can't fix it, please log a bug to the team that owns this control to fix this.

**Comment by craxal** [comment]
After some investigation, styling the existing button doesn't appear to be an easy task. I see two possible options:

1. Use CSS styling to remove the clear button. This is the easiest solution and lowest impact. Since you can manually select existing text and delete it, removing the button wouldn't be a big deal.
2. Add buttons to make the search input look and behave similarly to the lefthand side. Not too complicated, still relatively low cost, but more than just removing the button entirely.
