### ISSUE TITLE
The error message is not localized when typing an invalid query in the table text editor

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5221]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211126.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**Language:** All languages
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Français' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a table -> Click 'Query' -> Click 'Text editor'.
5. Input an invalid query in the text editor -> Click 'Execute query (F5)'.
6. There is an error -> Check whether the error message is localized.

## Expected Experience ##
The error message is localized.
![image](https://user-images.githubusercontent.com/87792676/143552774-5cc8fc77-bd4b-46e9-9b68-9539ebd13a36.png)

## Actual Experience ##
The error message is not localized.
![image](https://user-images.githubusercontent.com/87792676/143552848-6a5aa219-26c1-4ab8-a19c-ae2d37f8b6d6.png)

**Comment by MRayermannMSFT** [comment]
@craxal make sure this is not hardcoded. If it isn't, feel free to move this to loc milestone and we can revisit later to make sure it got translated.

**Comment by craxal** [comment]
The message comes straight from Azure; it is not hardcoded, and we cannot localize it.

I believe Azure requests can send the desired language as an HTTP header. We may want to consider setting that header in all requests.

**Comment by craxal** [comment]
@MRayermannMSFT Possibly? Depends on how much work it takes to set the language for responses.

**Comment by craxal** [comment]
This may have been fixed while migrating the explorer to the extension. Will verify.

**Comment by v-kellyluo** [comment]
This issue still reproduces on the build main/20220607.2.

**Comment by craxal** [comment]
@v-kellyluo I've merged several table extension updates over the last few weeks. Last I checked, the message was localized again. Can you please verify?

**Comment by v-kellyluo** [comment]
@craxal , this issue still reproduces on the lasted build main/20220707.4.😢
![image](https://user-images.githubusercontent.com/87792676/177674397-3ac5ed62-7ec0-499b-bc41-2076601bb19c.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220712.1. Fixed.
