### ISSUE TITLE
Navigating to a deep-level directory displays an extra paths in the address box after creating a snapshot for the file share

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#63]
**OS Version:** Win10 Enterprise(64 bits)
**Storage Explorer:** Storage Explorer_Windows_20180407.1

**Repro Steps:**
1. Launch Storage Explorer and expand Storage Accounts. 
2. Open one file share and navigate to a deep-level directory.
3. Create a snapshot for the file share.
4. Check the opened directory path next to the combo box after creating snapshot successfully.

**Expect:**
No extra path displays. 

**Actual:** 
There displays an extra and truncated paths. --Please see attachment truncated.png.

**More Info:**
1. This issue also reproduces on previous release 0.9.6.
2. This issue also reproduces on Linux/Mac.

This is FTS bug: 596795

**Comment by craxal** [comment]
Unable to reproduce. May have been fixed in 1.0.0, since I added some changes that limits the size of the combo box.

@v-xuanzh Please verify. If you're still able to reproduce, please reopen this bug and provide the file share and path that you reproduced this with.

**Comment by v-xuanzh** [comment]
Hi Craig,
This issue still reproduces on **master/20180425.3**. So reopen this issue.

**Reproduced file path:**
1. Open one file share which no snapshots.
2. Go to the 'New Directory>New Directory> New Directory>New Directory'.(Or go to a deep-level file)
3. Create a snapshot for the file share.
![path](https://user-images.githubusercontent.com/34729022/39290166-407c509c-491e-11e8-8570-c06dcc9dd51f.png)

**Comment by craxal** [comment]
OK, we see it now. This isn't very serious. The user can just navigate to another path, refresh, or reload the tab.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201222.4. The current behavior is like below screenshot.
![image](https://user-images.githubusercontent.com/41351993/103128983-17b8de00-46d2-11eb-9dfb-5d8760eb491a.png)

**Comment by craxal** [comment]
@v-xianya What happens when you resize the window?

**Comment by v-xianya** [comment]
@craxal This issue doesn't reproduce when resizing the window.

**Comment by v-xianya** [comment]
This [issue](https://github.com/microsoft/AzureStorageExplorer/issues/63#issuecomment-751213170) still reproduces on the latest main build 20210915.4.
![testissue](https://user-images.githubusercontent.com/41351993/133403909-c79db116-5e30-4d33-9fb7-7fa801269a55.gif)

**Comment by JasonYeMSFT** [comment]
The problem is fixed in the latest version of Storage Explorer.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20220728.1. Fixed.
