### ISSUE TITLE
Cannot see the filter icon if open the 'Search for resources of type' panel under 'High Contrast - Black/White' theme 

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7574]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231212.6
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Launch storage explorer -> Set the theme to 'High Contrast - Black'.
2. Open the 'Search for resources of type' panel.
3. Check whether we can see the filter icon.

## Expected Experience ##
We can see the filter icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bfa6d10d-3861-4fa4-af88-9a3915c6001a)

## Actual Experience ##
Cannot see the filter icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ee55e15c-295d-4f75-9709-8259c99bc370)

**Comment by JasonYeMSFT** [comment]
I merged a fix for this issue.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231213.5, it still reproduces. So, we are going to reopen it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/653fe7f9-0b90-42d5-a240-a707b9777482)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231214.4. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/344d06b6-6dd8-4a23-a3ea-46ec76014595)
