### ISSUE TITLE
Unable to add Cosmos DB emulator with custom port

### ISSUE THREAD

**Issue by AinslieCleverdon** [microsoft/AzureStorageExplorer#79]
**Storage Explorer Version:**
1.0.0

**OS Version:**
Windows Server 2012 R2 Standard

**Steps to Reproduce:**
1. Under '(Local and Attached)' right click 'Cosmos DB Accounts' and select 'Connect to Cosmos DB Emulator'
2. Change the port number of the account endpoint in the connection string

**Expected Experience:**
I can click next to continue creation of the connection

**Actual Experience:**
The following error is shown:
Invalid format connection string for SQL API.

**Comment by GarrettDavis** [comment]
I'm experiencing the same problem with 1.1.0 as well.  I need to use an alternate port because I have a another service running my local development environment that uses 8081.

I was able to hack `AccountConfigPanelViewModel.js` to set the default connection string to one with my custom port in it (line 18).  The problem is that the `_sqlConnectionStringFormat` doesn't match the localhost path when the connection string is validated after editing the connection string.  If you leave the string alone and click Next, it doesn't try to validate the connection string.

I would propose that the real fix is to replace line 14 which is
```
    _this._sqlConnectionStringFormat = /AccountEndpoint=https?:\/\/.+\.documents\.azure\.com:443\/?;AccountKey=.+;/;
```
with the following:
```
    _this._sqlConnectionStringFormat = _this.dialogViewModel.isEmulator
      ? /AccountEndpoint=https?:\/\/localhost:\d{3,5}\/?;AccountKey=.+;/
      : /AccountEndpoint=https?:\/\/.+\.documents\.azure\.com:443\/?;AccountKey=.+;/;
```
Which works for me ;)

**Comment by carlrabbit** [comment]
Please don't forget local docker deployments. Basically any ip address could be used as well.

**Comment by djlan** [comment]
Fixed. It will be shipped in coming release.

**Comment by GarrettDavis** [comment]
I just downloaded 1.2.0 and this is not fixed.  I tried   Inspecting the code for `AccountConfigPanelViewModel.js` indicates that this change was not implemented and you are still only allowed to change the connection string to an "Azure Cloud" connection string (*.documents.azure.com:443).  Did it not make it into the 1.2.0 milestone?  I didn't see it in the Readme for version 1.2.0.  Will this be in the next release (1.3.0)?  In the meantime, I'm just going to have to hack the code again to get it to work.

**Comment by ziyel** [comment]
@GarrettDavis Yes. We will release the fix in next release. Reopen the issue. 
Sorry for the confusion, and thanks a lot for your deep investigation.

**Comment by MRayermannMSFT** [comment]
@ziyel , did this make 1.3.0?

**Comment by ziyel** [comment]
@MRayermannMSFT , yes!

**Comment by MRayermannMSFT** [comment]
Ok, then closing the issue. Thank you. 😄

**Comment by darekzuk** [comment]
I have just installed version 1.4.0, and this is still not fixed. Connection string with endpoint something.documents.azure.com:443 is accepted, and something.documents.microsoftazure.de (german cloud) is not accepted.

**Comment by BobvdS** [comment]
I have the same issue when trying to connect to cosmos in a government tenant where the url is not .com but .us

**Comment by ziyel** [comment]
Thanks for the feedback. We will fix this in next release.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
