### ISSUE TITLE
Nothing happens after clicking 'Retry All' for the failed activities of renaming blob 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#992]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181211.1
**Commit**: 2455da61
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one non - ADLS Gen2 account.
2. Open one blob container then upload a blob to it.
3. Create snapshots for the uploaded blob -> Try to rename the blob(_Fail to rename it due to the blob has snapshots_ ).
4. Delete all the created snapshots -> Click 'Retry All' link next to the failed renaming activities.

#### Expected Experience: ####
Succeed to retry the failed activities.

#### Actual Experience: ####
Nothing happens after clicking 'Retry All'.
![retryall](https://user-images.githubusercontent.com/34729022/49790871-33125400-fd6a-11e8-8224-c6855ac30a2b.png)

**Comment by MRayermannMSFT** [comment]
I believe this has been fixed. @v-xuanzh , can you please verify? Thanks!

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,This issue still reproduces on the latest master build. Could you help to take look it?

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
